kind: pipeline
name: default

platform:
    os: linux
    arch: amd64

steps:

- name: build
  image: golang:latest
  commands:
    - go build -o freitagsfoo ./...

- name: docker
  image: plugins/docker
  settings:
      tags:
        - latest
      repo: registry.darknebu.la/chaosdorf/freitagsfoo
      registry: registry.darknebu.la
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

